repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-merge-conflict
  - id: check-json
  - id: check-yaml
    args: [--unsafe]
  - id: end-of-file-fixer

- repo: https://github.com/ambv/black
  rev: 22.6.0
  hooks:
  - id: black
    language_version: python3.10

- repo: git@github.com:humitos/mirrors-autoflake.git
  rev: v1.1
  hooks:
  - id: autoflake
    args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort
    exclude: migrations/, *.csv
